// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// knapsack_dynamic_program
IntegerVector knapsack_dynamic_program(NumericVector values, IntegerVector weights, int capacity);
RcppExport SEXP _dflasso_knapsack_dynamic_program(SEXP valuesSEXP, SEXP weightsSEXP, SEXP capacitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type capacity(capacitySEXP);
    rcpp_result_gen = Rcpp::wrap(knapsack_dynamic_program(values, weights, capacity));
    return rcpp_result_gen;
END_RCPP
}
// column_correlation_abs
Rcpp::NumericVector column_correlation_abs(const arma::mat& features, const arma::vec& response);
RcppExport SEXP _dflasso_column_correlation_abs(SEXP featuresSEXP, SEXP responseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type response(responseSEXP);
    rcpp_result_gen = Rcpp::wrap(column_correlation_abs(features, response));
    return rcpp_result_gen;
END_RCPP
}
// shortest_path_dijkstra
IntegerVector shortest_path_dijkstra(IntegerVector from, IntegerVector to, NumericVector cost, int n_nodes, int origin, int destination);
RcppExport SEXP _dflasso_shortest_path_dijkstra(SEXP fromSEXP, SEXP toSEXP, SEXP costSEXP, SEXP n_nodesSEXP, SEXP originSEXP, SEXP destinationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cost(costSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< int >::type origin(originSEXP);
    Rcpp::traits::input_parameter< int >::type destination(destinationSEXP);
    rcpp_result_gen = Rcpp::wrap(shortest_path_dijkstra(from, to, cost, n_nodes, origin, destination));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dflasso_knapsack_dynamic_program", (DL_FUNC) &_dflasso_knapsack_dynamic_program, 3},
    {"_dflasso_column_correlation_abs", (DL_FUNC) &_dflasso_column_correlation_abs, 2},
    {"_dflasso_shortest_path_dijkstra", (DL_FUNC) &_dflasso_shortest_path_dijkstra, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_dflasso(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
